# Copyright 2019 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Download gcloud SDK
  ansible.builtin.get_url:
    url: https://sdk.cloud.google.com/
    dest: /tmp/install-gcloud.sh
    mode: "0700"

- name: Execute install-gcloud.sh
  ansible.builtin.command: bash -o errexit -o pipefail /tmp/install-gcloud.sh --disable-prompts --install-dir=/
- name: Remove install-gcloud.sh
  ansible.builtin.file:
    path: /tmp/install-gcloud.sh
    state: absent

- name: Find all files in /google-cloud-sdk/bin/
  ansible.builtin.find:
    paths: /google-cloud-sdk/bin/
  register: find

- name: Create symlinks to /bin
  become: true
  ansible.builtin.file:
    src: "{{ item.path }}"
    path: /bin/{{ item.path | basename }}
    state: link
  with_items: "{{ find.files }}"

- name: Install cloud-init packages
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - cloud-init
      - cloud-utils-growpart
  when: ansible_os_family == "RedHat"

- name: Disable Hyper-V KVP protocol daemon on Ubuntu
  ansible.builtin.systemd:
    name: hv-kvp-daemon
    state: stopped
    enabled: false
  when: ansible_os_family == "Debian"
